"use client";
import {useEffect,useRef,useState,type FormEvent,type MouseEvent} from "react";
import {ArrowUpRight,ArrowLeft,ArrowRight,Plus,Search,FolderOpen,Layers3,Library,Settings2,Check,Archive,FileText,Info,Menu,ExternalLink,Download} from "lucide-react";
import {references,directions,seedProjects,type Reference} from "../lib/data";
import {createProject,updateInput,confirmDirection,reviewAsset,decodeProjects,stages,projectStage,canProduce,finals,type Project,type Stage,type Asset} from "../lib/workflow";
import {Button,Empty,Heading,Modal,Photo,StepLink} from "../components/ui";
import {StageView,ReferenceView,downloadAsset,type Actions} from "../components/stages";
const STORAGE="cis-preview-workspace-v1";
type Route={view:string;id?:string;stage:Stage;q:string;filter:string};
function parseRoute():Route{const h=window.location.hash.slice(1)||"/projects";const[path,query]=h.split("?");const parts=path.split("/").filter(Boolean);const s=new URLSearchParams(query);return {view:parts[0]||"projects",id:parts[1],stage:stages.some(s=>s[0]===parts[2])?parts[2] as Stage:"product",q:s.get("q")||"",filter:s.get("filter")||"全部"};}
function now(){return new Date().toISOString();}
export default function Page(){
 const[projects,setProjects]=useState<Project[]>(seedProjects),[route,setRoute]=useState<Route>({view:"projects",stage:"product",q:"",filter:"全部"});
 const[ready,setReady]=useState(false),[saveError,setSaveError]=useState(""),[toast,setToast]=useState(""),[dirty,setDirty]=useState(false);
 const[dialog,setDialog]=useState<"new"|"help"|null>(null),[refDetail,setRefDetail]=useState<Reference|null>(null),[review,setReview]=useState<Asset|null>(null),[note,setNote]=useState(""),[menu,setMenu]=useState(false);
 const[sort,setSort]=useState("updated"),[q,setQ]=useState(""),[filter,setFilter]=useState("全部");
 const blockedStorage=useRef(false); const stateRef=useRef({projects,route});stateRef.current={projects,route};
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE);if(raw)setProjects(decodeProjects(raw));}catch{blockedStorage.current=true;setSaveError("本地数据读取失败。当前显示示例，已有存储未被覆盖；如需保存新修改，请先导出可见数据或使用其他浏览器。");}setRoute(parseRoute());setReady(true);const change=()=>{setRoute(parseRoute());setMenu(false);setDirty(false);};window.addEventListener("hashchange",change);return()=>window.removeEventListener("hashchange",change);},[]);
 useEffect(()=>{setQ(route.q);setFilter(route.filter);document.title=(route.id?projects.find(p=>p.id===route.id)?.name||"项目":route.view==="references"?"参考库":route.view==="assets"?"资产库":route.view==="jobs"?"生产任务":route.view==="settings"?"工作空间设置":"工作台")+" · CIS";},[route,projects]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(""),4500);return()=>clearTimeout(id);},[toast]);
 useEffect(()=>{if(!dirty)return;const handler=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue="";};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler);},[dirty]);
 useEffect(()=>{
  type Tool={name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};
  const context=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const controller=new AbortController();
  try{void Promise.resolve(context.registerTool({name:"read_cis_preview_context",description:"Read the current CIS local preview view and project summaries. Demo data only; no changes.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=="object"||Array.isArray(input)||Object.keys(input).length)throw new Error("Expected an empty object");return {demo:true,view:stateRef.current.route,projects:stateRef.current.projects.map(p=>({id:p.id,name:p.name,stage:projectStage(p),revision:p.revision,archived:p.archived}))};}},{signal:controller.signal})).catch(()=>{});}catch{}
  return()=>controller.abort();
 },[]);
 const p=route.view==="projects"&&route.id?projects.find(p=>p.id===route.id):undefined;
 function persist(next:Project[],message="已保存到当前浏览器"){
  setProjects(next);try{if(blockedStorage.current)throw new Error("read");localStorage.setItem(STORAGE,JSON.stringify({version:1,projects:next}));setSaveError("");setToast(message);}catch{setSaveError("本地保存失败，当前修改仅在本次页面中保留。请导出文案后再关闭页面。");}
 }
 function modify(next:Project,message?:string){persist(projects.map(p=>p.id===next.id?next:p),message);}
 function safeRun(fn:()=>void){try{fn();}catch(e){setToast(e instanceof Error?e.message:"操作未完成");}}
 const a:Actions={
 input(patch){if(p&&!p.archived)modify(updateInput(p,patch,now()));},
 confirm(id){if(p)safeRun(()=>modify(confirmDirection(p,id,now()),"方向已确认，可以进入创意板"));},
 produce(){if(!p||!canProduce(p))return;const d=directions.find(d=>d.id===p.direction)!;const stamp=now();const asset:Asset={id:crypto.randomUUID(),text:d.name+"\n\n"+d.summary+"\n\n创作需求："+p.brief+"\n\n表达策略："+d.strategy+"\n\n注意：本地模板演示，所有材料、性能和正式产品信息仍需知识验证。",revision:p.revision,createdAt:stamp,status:"pending",note:""};modify({...p,assets:[asset,...p.assets],updatedAt:stamp},"文案演示已制作，等待人工评审");window.location.hash="/projects/"+p.id+"/review";},
 review(asset){setReview(asset);setNote(asset.note);},openReference:setRefDetail,notify:setToast,dirty:setDirty
 };
 function navGuard(e:MouseEvent<HTMLDivElement>){const target=e.target as HTMLElement;if(target.closest("a[href]")&&dirty){if(!window.confirm("需求尚未保存。放弃本次未保存修改并离开？"))e.preventDefault();else setDirty(false);}}
 function filterChange(value:string,query=q){setFilter(value);const params=new URLSearchParams();if(value!=="全部")params.set("filter",value);if(query)params.set("q",query);const hash="/projects"+(params.size?"?"+params:"");history.replaceState(null,"","#"+hash);}
 function search(value:string){setQ(value);filterChange(filter,value);}
 const allAssets=projects.flatMap(p=>p.assets.map(a=>({p,a})));
 const filtered=projects.filter(p=>(filter==="全部"||(filter==="已归档"?p.archived:!p.archived))&&(p.name+p.category+p.brief).toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name,"zh"):b.updatedAt.localeCompare(a.updatedAt));
 const stageIndex=stages.findIndex(s=>s[0]===route.stage);
 const stageLabel=stages[stageIndex]?.[1]||"产品理解";
 function newProject(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const name=String(fd.get("name")||"").trim();if(!name){setToast("请输入项目名称");return;}const next=createProject(crypto.randomUUID(),name,String(fd.get("category")),now());persist([next,...projects],"项目已创建");setDialog(null);window.location.hash="/projects/"+next.id+"/product";}
 return <div onClickCapture={navGuard}><a className="skip-link" href="#main" onClick={e=>{e.preventDefault();document.getElementById("main")?.focus();}}>跳到主要内容</a>
 <header className="topbar"><a className="brand" href="#/projects" aria-label="CIS 工作台"><b>CIS<span>01</span></b><span>CREATIVE<br/>INTELLIGENCE STUDIO</span></a><nav aria-label="全局导航">{[["projects","工作台"],["references","参考库"],["assets","资产库"]].map(([v,n])=><a key={v} className={route.view===v?"active":""} aria-current={route.view===v?"page":undefined} href={"#/"+v}>{n}</a>)}</nav><button className="preview-tag" onClick={()=>setDialog("help")}>首版预览 <Info size={12}/></button><button className="avatar" aria-label="查看预览说明" onClick={()=>setDialog("help")}>C</button><button className="mobile-menu icon-button" onClick={()=>setMenu(!menu)} aria-label="展开导航" aria-expanded={menu}><Menu size={18}/></button></header>
 <div className="app-frame"><aside className={"sidebar "+(menu?"mobile-open":"")} aria-label={p?"项目阶段":"工作空间"}>
 {p?<><a className="back-projects" href="#/projects"><ArrowLeft size={14}/>全部项目</a><h2 className="project-sidebar-title">{p.name}</h2><span className="badge sidebar-demo">本地项目 · r{p.revision}</span><nav className="stage-nav">{stages.map(([key,label],i)=><div key={key}>{[0,2,7].includes(i)&&<div className="nav-group">{i===0?"理解":i===2?"构思":"制作"}</div>}<a href={"#/projects/"+p.id+"/"+key} className={"stage-link "+(route.stage===key?"selected":"")} aria-current={route.stage===key?"step":undefined}><span>{String(i+1).padStart(2,"0")}</span>{label}{route.stage===key&&<span className="stage-current"/>}</a></div>)}</nav></>:<><div className="workspace-label">工作空间 <span>01</span></div><a href="#/projects" className={"side-link "+(route.view==="projects"?"selected":"")}><FolderOpen size={18}/>全部项目 <span>{String(projects.length).padStart(2,"0")}</span></a><a href="#/references" className={"side-link "+(route.view==="references"?"selected":"")}><Library size={18}/>参考收藏 <span>03</span></a><a href="#/jobs" className={"side-link "+(route.view==="jobs"?"selected":"")}><Layers3 size={18}/>生产任务 <span>{allAssets.length}</span></a></>}
 <div className="side-bottom">{!p&&<><span className="small-label">YOUR CREATIVE PROCESS</span><p>每个好创意，<br/>都有迹可循。</p></>}<a href="#/settings" className={"side-link "+(route.view==="settings"?"selected":"")}><Settings2 size={18}/>工作空间设置</a></div></aside>
 <main id="main" tabIndex={-1} className={"main "+(p?"project-main":"")}>
 {saveError&&<div className="notice error" role="alert">{saveError}</div>}
 {!ready?<div className="loading-state" role="status">正在读取本地工作空间…</div>:route.view==="projects"&&!route.id?<><div className="eyebrow">WORKSPACE / 项目</div><div className="page-heading"><div><h1>让下一次创作，<br/><span className="muted">从理解开始。</span></h1><p>整理产品、发现参考，将灵感推进为清晰的创意方向。</p></div><Button primary onClick={()=>setDialog("new")}><Plus size={18}/>新建项目</Button></div>
 <div className="toolbar"><div className="tabs">{["全部","进行中","已归档"].map(t=><button key={t} aria-pressed={filter===t} className={filter===t?"active":""} onClick={()=>filterChange(t)}>{t==="全部"?"全部项目":t}<small>{projects.filter(p=>t==="全部"||(t==="已归档"?p.archived:!p.archived)).length}</small></button>)}</div><div className="search"><Search size={17}/><input aria-label="搜索项目" placeholder="搜索项目…" value={q} onChange={e=>search(e.target.value)}/></div><select className="sort-select" aria-label="项目排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated">最近更新</option><option value="name">项目名称</option></select></div>
 <div className="section-line"><span>最近的创作 / {String(filtered.length).padStart(2,"0")}</span><span>LOCAL WORKSPACE</span></div>
 {filtered.length?<div className="project-list">{filtered.map((p,i)=><a href={"#/projects/"+p.id+"/"+projectStage(p)} className={"project-row "+(p.cover?"with-image":"")} key={p.id}><span className="project-number">{String(i+1).padStart(2,"0")}</span>{p.cover&&<Photo className="project-cover" src={references.find(r=>r.id===p.cover)?.image||"/images/trail.jpg"} alt="摄影参考封面"/>}<div><span className="small-label">{p.category} · {p.id.startsWith("demo")?"示例项目":"本地项目"}</span><h2>{p.name}</h2><p>{p.brief||"从一个创作意图开始，建立你的第一份产品上下文。"}</p></div><span className="badge">{p.archived?"已归档":stages.find(s=>s[0]===projectStage(p))?.[1]}</span><ArrowUpRight size={22}/></a>)}</div>:<Empty title="没有匹配的项目" description="调整搜索与状态筛选，或开始一个新项目。"><Button onClick={()=>{search("");filterChange("全部","");}}>清除筛选</Button></Empty>}
 <div className="bottom-note"><span>DEMO WORKSPACE</span><p>示例项目不代表真实产品事实。修改仅保存在当前浏览器。</p><span>KNOWLEDGE → DIRECTION → CREATION</span></div></>
 :p?<><div className="project-breadcrumb"><a href="#/projects">项目</a><span>/</span><span>{p.name}</span><span>/</span><span>{stageLabel}</span></div><div className="mobile-stage"><select aria-label="项目阶段" value={route.stage} onChange={e=>{if(!dirty||window.confirm("放弃未保存修改并切换阶段？"))window.location.hash="/projects/"+p.id+"/"+e.target.value;}}>{stages.map(([key,label],i)=><option key={key} value={key}>{String(i+1).padStart(2,"0")} {label}</option>)}</select></div>
 <Heading eyebrow={String(stageIndex+1).padStart(2,"0")+" / "+route.stage.toUpperCase().replace("-"," ")} title={stageLabel} description={route.stage==="references"?"寻找值得借鉴的视觉语言，而不只寻找相似的图片。":route.stage==="directions"?"让产品、意图和参考，收敛成一个值得执行的选择。":undefined} action={<span className="badge">{dirty?"未保存":p.archived?"已归档":"本地草稿"} · r{p.revision}</span>}/>
 {p.archived?<div className="notice">当前项目已归档。<button className="text-link" onClick={()=>modify({...p,archived:false,updatedAt:now()},"项目已恢复")}>恢复项目<ArrowRight size={16}/></button></div>:null}
 <fieldset className="stage-fieldset" disabled={p.archived}><StageView key={p.id+route.stage} stage={route.stage} p={p} a={a}/></fieldset>
 <footer className="stage-footer">{stageIndex>0?<StepLink href={"#/projects/"+p.id+"/"+stages[stageIndex-1][0]}>上一阶段 · {stages[stageIndex-1][1]}</StepLink>:<span>产品事实优先 · 未知保持未知</span>}{stageIndex<stages.length-1&&<StepLink href={"#/projects/"+p.id+"/"+stages[stageIndex+1][0]}>下一阶段 · {stages[stageIndex+1][1]}</StepLink>}<button className="archive-action" onClick={()=>{if(dirty){setToast("请先保存当前修改");return;}modify({...p,archived:!p.archived,updatedAt:now()},p.archived?"已恢复":"已归档，可随时恢复");}}><Archive size={14}/>{p.archived?"恢复项目":"归档项目"}</button></footer></>
 :route.view==="references"?<><Heading eyebrow="LIBRARY / 参考库" title="好创意，从好的观察开始。" description="收集视觉语言，保留每一次灵感的来源。"/><ReferenceView a={a}/><div className="notice">在项目的“参考发现”中，可以将这些摄影参考加入当前创意组合。<StepLink href="#/projects">进入项目</StepLink></div></>
 :route.view==="assets"?<><Heading eyebrow="LIBRARY / 资产库" title="让创作积累下来。" description="在这里查看当前浏览器内的文案演示与审核状态。"/>{allAssets.length?<div className="global-rows">{allAssets.map(({p,a})=><div className="global-row" key={a.id}><FileText size={22}/><div><h3>{a.text.split("\n")[0]}</h3><p>{p.name} / r{a.revision} / {a.status==="approved"?"人工通过":a.status==="rejected"?"已淘汰":"待评审"}</p></div><a className="button" href={"#/projects/"+p.id+"/review"}>打开评审</a>{a.status==="approved"&&<button className="icon-button" aria-label="导出已通过文案" onClick={()=>downloadAsset(p,a)}><Download size={18}/></button>}</div>)}</div>:<Empty title="尚无创作资产" description="完成一份文案演示后，它会出现在这里。摄影参考请到参考库查看。"><StepLink href="#/projects">继续创作</StepLink></Empty>}</>
 :route.view==="jobs"?<><Heading eyebrow="PRODUCTION / 任务" title="每一步创作，都有进展。" description="以下只记录本地模板制作。真实生成队列尚未接入。"/>{allAssets.length?<div className="global-rows">{allAssets.map(({p,a})=><a className="global-row" href={"#/projects/"+p.id+"/review"} key={a.id}><Check size={22}/><div><h3>{p.name} · 文案演示</h3><p>本地模板制作完成 · {new Date(a.createdAt).toLocaleString("zh-CN")}</p></div><span className="badge">{a.status==="pending"?"待人工评审":a.status==="approved"?"已通过":"已淘汰"}</span><ArrowUpRight size={20}/></a>)}</div>:<Empty title="还没有生产记录" description="确认方向后，可以制作文案演示并体验审核流程。"><StepLink href="#/projects">选择项目</StepLink></Empty>}</>
 :route.view==="settings"?<><Heading eyebrow="WORKSPACE / 设置" title="工作空间设置" description="首版预览只使用本地演示数据，不连接真实业务系统。"/><section className="settings-list">{[["产品知识平台","正式产品事实、版本与来源","未连接"],["图文生成服务","真实模型调用与生成结果","未连接"],["NAS 资产存储","媒体保存与团队共享","未连接"],["团队身份与权限","成员、角色和项目授权","未配置"],["浏览器本地工作空间","当前设备内的需求、选择和演示产物","已启用"]].map(([name,desc,status])=><div className="setting-row" key={name}><div><h3>{name}</h3><p>{desc}</p></div><span className="badge">{status}</span></div>)}</section><div className="notice">这里的连接状态用于说明首版能力边界，不收集密钥。Sites 的访问控制与未来业务角色权限是两层独立机制。</div><a className="text-link" href="https://github.com/FlipBelt/creative-intelligence-studio" target="_blank" rel="noreferrer">查看项目文档<ExternalLink size={16}/></a></>
 :<Empty title="找不到这个页面或本地项目" description="项目可能只保存在另一台设备或另一个浏览器中。"><StepLink href="#/projects">返回工作台</StepLink></Empty>}
 </main></div>
 {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}
 {dialog==="new"&&<Modal title="新建创意项目" onClose={()=>setDialog(null)}><p className="muted">先给这次创作一个名字，其他细节可以慢慢补充。</p><form onSubmit={newProject}><label className="field">项目名称 <span>必填</span><input name="name" required maxLength={80} placeholder="例如：秋日户外系列" autoFocus/></label><label className="field">创作类型<select name="category"><option>品牌影像</option><option>产品叙事</option><option>编辑专题</option><option>社交内容</option></select></label><p className="caption">项目只保存在当前浏览器。请勿录入机密或真实身份信息。</p><div className="modal-actions"><Button onClick={()=>setDialog(null)}>取消</Button><Button primary type="submit">创建项目<ArrowRight size={16}/></Button></div></form></Modal>}
 {dialog==="help"&&<Modal title="关于首版预览" onClose={()=>setDialog(null)}><p>可以新建项目、编辑需求、选择参考、比较方向，体验本地文案演示与人工审核。</p><div className="notice">预览内容仅保存在当前浏览器，不与团队同步。AI、知识平台、NAS 和业务身份系统尚未连接。</div><p>示例项目为虚构创作场景。摄影参考保留真实来源，不作为产品图片或性能证据。</p><a className="text-link" href="#/settings" onClick={()=>setDialog(null)}>查看工作空间设置<ArrowRight size={16}/></a></Modal>}
 {refDetail&&<Modal title={refDetail.name} wide onClose={()=>setRefDetail(null)}><div className="reference-detail"><Photo src={refDetail.image} alt={refDetail.name}/><div><span className="badge">摄影参考 · 非产品素材</span><h3>值得观察的部分</h3><p>{refDetail.description}</p><p className="muted">{refDetail.dimension}</p><hr/><p>摄影：{refDetail.author}</p><a className="text-link" href={refDetail.url} target="_blank" rel="noreferrer">查看 Pexels 原始来源<ExternalLink size={16}/></a><p className="caption">不代表摄影者、人物或品牌为当前项目背书。</p></div></div></Modal>}
 {review&&p&&<Modal title="评审文案演示" wide onClose={()=>setReview(null)}><div className="review-layout"><div className="review-copy"><span className="small-label">本地模板 · 输入 r{review.revision}</span><pre>{review.text}</pre></div><div><span className="badge">AI 评审未接入</span><h3>由你做最后判断</h3><p>检查表达是否符合需求，是否包含无依据的产品事实。</p><label className="field">审核备注<textarea value={note} maxLength={1000} rows={4} onChange={e=>setNote(e.target.value)} placeholder="记录保留、修改或淘汰的原因"/></label>{review.revision!==p.revision&&<p className="notice error">输入版本已改变，此版本不能新批准。</p>}<div className="modal-actions"><Button onClick={()=>safeRun(()=>{modify(reviewAsset(p,review.id,"rejected",note,now()),"已记录淘汰结果");setReview(null);})}>淘汰</Button><Button primary disabled={!canProduce(p)||review.revision!==p.revision} onClick={()=>safeRun(()=>{modify(reviewAsset(p,review.id,"approved",note,now()),"人工通过，已进入最终资产");setReview(null);})}><Check size={16}/>通过并留存</Button></div></div></div></Modal>}
 </div>;
}
