import {test} from "node:test";
import assert from "node:assert/strict";
import {average,isFeatured,reviewSkill,reviewWork,decodeStudio,emptyStudio,type Skill,type Work} from "./studio.ts";
const skill:Skill={id:"v1",family:"a",version:1,name:"示例",description:"测试",media:"图片",filename:"test.md",content:"text",createdAt:"now",status:"pending",audit:[]};
const work:Work={id:"w1",family:"w",version:1,title:"测试",category:"产品展示",product:"",author:"local",image:"data:image/png;base64,eA==",createdAt:"now",status:"pending",scores:null,reason:"",factsChecked:false,audit:[]};
test("员工不能发布技能，管理员必须审核具体待审版本",()=>{assert.throws(()=>reviewSkill([skill],"v1","published","employee","ok","now"));assert.throws(()=>reviewSkill([skill],"v1","published","admin","","now"));const s=reviewSkill([skill],"v1","published","admin","检查通过","now");assert.equal(s[0].status,"published");assert.equal(s[0].audit.length,1);assert.throws(()=>reviewSkill(s,"v1","published","admin","again","now"));});
test("新技能版本待审期间不替换已发布版本，通过后才替换",()=>{const first={...skill,status:"published" as const};const next={...skill,id:"v2",version:2};const waiting=[first,next];assert.equal(waiting.filter(s=>s.status==="published")[0].id,"v1");const approved=reviewSkill(waiting,"v2","published","admin","新版检查通过","now");assert.equal(approved[0].status,"disabled");assert.equal(approved[1].status,"published");assert.equal(approved[0].content,skill.content);});
test("作品未评分不计0，高分不能绕过审核和事实检查",()=>{assert.equal(average(null),null);assert.equal(isFeatured(work,4),false);assert.equal(isFeatured({...work,scores:[5,5,5,5]},4),false);assert.throws(()=>reviewWork(work,"published",[5,5,5,5],false,"原因","admin","now"));assert.throws(()=>reviewWork(work,"published",[5,5,5,5],true,"原因","employee","now"));const approved=reviewWork(work,"published",[4,5,4,5],true,"检查通过","admin","now");assert.equal(average(approved.scores),4.5);assert.equal(isFeatured(approved,4),true);assert.equal(isFeatured(approved,5),false);});
test("退回作品不进入精选，非法评分和损坏存储拒绝",()=>{assert.throws(()=>reviewWork(work,"published",[6,5,5,5],true,"原因","admin","now"));const rejected=reviewWork(work,"rejected",[],false,"待修改","admin","now");assert.equal(isFeatured(rejected,1),false);assert.deepEqual(decodeStudio(JSON.stringify(emptyStudio())),emptyStudio());assert.throws(()=>decodeStudio('{"version":2}'));assert.throws(()=>decodeStudio(JSON.stringify({...emptyStudio(),skills:[{...skill,status:"approved"}]})));});

test("技能审批不能用旧待审版本覆盖已发布新版",()=>{const newer={...skill,id:"v3",version:3,status:"published" as const};assert.throws(()=>reviewSkill([skill,newer],"v1","published","admin","过期审核","now"));});
test("作品再次评分追加评分快照，不改变历史审核分数",()=>{const first=reviewWork(work,"published",[4,4,4,4],true,"第一次","admin","t1");const second=reviewWork(first,"published",[5,5,5,5],true,"第二次","admin","t2");assert.deepEqual(second.audit[0].scores,[4,4,4,4]);assert.deepEqual(second.audit[1].scores,[5,5,5,5]);});
