"use client";
import {useState,type FormEvent} from "react";
import {Plus,ArrowRight,ShieldCheck,Upload,FileText} from "lucide-react";
import {reviewSkill,type Studio,type Skill,type DemoRole} from "../lib/studio";
import {Button,Empty,Heading,Modal} from "./ui";
export const statusName=(s:string)=>({pending:"待管理员审核",published:"已发布",rejected:"已退回",disabled:"已停用",superseded:"已被新版本替代"}[s]||s);
export function DemoRoleBar({role,setRole}:{role:DemoRole;setRole:(r:DemoRole)=>void}){return <div className="demo-role-bar"><div><ShieldCheck size={18}/><span>本地流程演示 · 尚无真实员工身份与团队权限</span></div><label>演示视角<select aria-label="演示视角" value={role} onChange={e=>setRole(e.target.value as DemoRole)}><option value="employee">员工</option><option value="admin">管理员</option></select></label></div>;}
export function SkillManager({data,save,role,setRole}:{data:Studio;save:(s:Studio)=>boolean;role:DemoRole;setRole:(r:DemoRole)=>void}){
 const[tab,setTab]=useState("已发布技能"),[q,setQ]=useState(""),[upload,setUpload]=useState<Skill|"new"|null>(null),[detail,setDetail]=useState<Skill|null>(null),[note,setNote]=useState(""),[error,setError]=useState("");
 const tabs=role==="admin"?["已发布技能","我的提交","待审核"]:["已发布技能","我的提交"];
 const active=tabs.includes(tab)?tab:"我的提交";
 const shown=data.skills.filter(s=>(active==="已发布技能"?s.status==="published":active==="待审核"?s.status==="pending":true)&&(s.name+s.description).includes(q));
 const current=data.skills.find(s=>s.id===detail?.id);
 function decide(decision:"published"|"rejected"|"disabled"){if(!current)return;try{const skills=reviewSkill(data.skills,current.id,decision,role,note,new Date().toISOString());if(save({...data,skills})){setDetail(null);setError("");}}catch(e){setError((e as Error).message);}}
 return <><Heading eyebrow="SKILLS / 可复用的方法" title="技能管理" description="把有效的方法沉淀下来，让下一次创作更容易。" action={<Button primary onClick={()=>setUpload("new")}><Plus size={17}/>上传技能</Button>}/><DemoRoleBar role={role} setRole={setRole}/><div className="notice">每次上传和版本更新都必须经过管理员审核。未发布技能不能被选择，当前预览不会执行任何技能文件。</div><div className="gallery-toolbar"><div className="tabs">{tabs.map(t=><button key={t} className={active===t?"active":""} onClick={()=>setTab(t)}>{t}{t==="待审核"?" · "+data.skills.filter(s=>s.status==="pending").length:""}</button>)}</div><input className="filter-input" aria-label="搜索技能" value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索名称与用途"/></div>{shown.length?<div className="skill-grid">{shown.map(s=><article className="skill-card" key={s.id}><div className="section-title"><FileText size={25}/><span className="badge">{statusName(s.status)}</span></div><h2>{s.name}</h2><p>{s.description}</p><span className="small-label">{s.media} · v{s.version} · 本地提交</span><div className="skill-actions"><Button onClick={()=>{setDetail(s);setNote("");setError("");}}>{role==="admin"&&s.status==="pending"?"审核此版本":"查看详情"}<ArrowRight size={16}/></Button><button className="text-link" onClick={()=>setUpload(s)}>提交新版本</button></div></article>)}</div>:<Empty title={active==="待审核"?"没有待审核技能":active==="已发布技能"?"还没有已发布技能":"没有匹配的提交"} description="上传技能后进入待审核。管理员通过具体版本后，才会出现在创作输入框中。"><Button onClick={()=>setUpload("new")}>提交第一个技能</Button></Empty>}
 {upload&&<Modal title={upload==="new"?"上传技能":"提交技能新版本"} onClose={()=>setUpload(null)}><SkillUpload previous={upload==="new"?undefined:upload} data={data} onSubmit={skill=>{if(save({...data,skills:[skill,...data.skills]})){setUpload(null);setTab("我的提交");}}}/></Modal>}
 {current&&<Modal title={current.name+" · v"+current.version} wide onClose={()=>setDetail(null)}><span className="badge">{statusName(current.status)}</span><p>{current.description}</p><p className="caption">{current.filename} · {current.media} · 仅文本展示，不执行</p><pre className="skill-source">{current.content}</pre>{current.audit.length>0&&<section><h3>审核记录</h3>{current.audit.map((item,i)=><p className="caption" key={i}>{new Date(item.at).toLocaleString("zh-CN")} · 管理员演示 · {statusName(item.action)}：{item.note}</p>)}</section>}{role==="admin"&&["pending","published"].includes(current.status)&&<><label className="field">审核说明<textarea value={note} maxLength={2000} onChange={e=>setNote(e.target.value)} placeholder="记录用途、内容、所需权限与版本变更的检查结果"/></label>{error&&<p className="notice error" role="alert">{error}</p>}<div className="modal-actions">{current.status==="pending"?<><Button disabled={!note.trim()} onClick={()=>decide("rejected")}>退回修改</Button><Button primary disabled={!note.trim()} onClick={()=>decide("published")}>通过并发布此版本</Button></>:<Button disabled={!note.trim()} onClick={()=>decide("disabled")}>停用此版本</Button>}</div></>}</Modal>}</>;
}
function SkillUpload({previous,data,onSubmit}:{previous?:Skill;data:Studio;onSubmit:(s:Skill)=>void}){
 const[name,setName]=useState(previous?.name||""),[description,setDescription]=useState(previous?.description||""),[media,setMedia]=useState(previous?.media||"图片"),[file,setFile]=useState<{name:string;content:string}|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 async function read(file:File|undefined){setFile(null);setError("");if(!file)return;if(!/\.(md|txt)$/i.test(file.name)||file.size>65536){setError("请选择64 KB以内的.md或.txt文件。预览暂不接收压缩包与执行文件。");return;}setLoading(true);try{const content=await file.text();if(!content.trim()||content.includes("\u0000"))throw new Error("文件不是有效文本");setFile({name:file.name,content});}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 function submit(e:FormEvent){e.preventDefault();if(!file||!name.trim()||!description.trim())return;const id=crypto.randomUUID();onSubmit({id,family:previous?.family||id,version:previous?Math.max(...data.skills.filter(s=>s.family===previous.family).map(s=>s.version))+1:1,name:name.trim(),description:description.trim(),media,filename:file.name,content:file.content,createdAt:new Date().toISOString(),status:"pending",audit:[]});}
 return <form onSubmit={submit}><p className="muted">上传后直接进入待审核。新版本获批前，原已发布版本保持可用。</p><label className="field">技能名称<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">用途、输入与所需权限<textarea required maxLength={2000} rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder="说明适用场景、必要输入、预期输出，以及是否需要外部工具"/></label><label className="field">适用类型<select value={media} onChange={e=>setMedia(e.target.value)}>{["图片","文案","视频","全部"].map(m=><option key={m}>{m}</option>)}</select></label><label className="field">技能文件（.md / .txt，最多64 KB）<input type="file" accept=".md,.txt,text/plain,text/markdown" onChange={e=>void read(e.target.files?.[0])}/></label>{loading&&<p role="status">正在读取文件…</p>}{file&&<p className="caption">已读取：{file.name}，提交后等待管理员审核。</p>}{error&&<p className="notice error" role="alert">{error}</p>}<Button primary type="submit" disabled={loading||!file||!name.trim()||!description.trim()}><Upload size={16}/>提交审核</Button></form>;
}
