"use client";
import {useState,type FormEvent} from "react";
import {ArrowRight,Check,LockKeyhole,Download,FileText,ArrowUpRight,BookOpen,Info} from "lucide-react";
import {references,directions,type Reference} from "../lib/data";
import {type Project,type Stage,type Asset,canProduce,directionGate,finals} from "../lib/workflow";
import {Button,Empty,Heading,Photo,ReferenceCard,StepLink} from "./ui";
export type Actions={input:(patch:Partial<Pick<Project,"brief"|"audience"|"output"|"product"|"bound"|"confirmed"|"refs">>)=>void;confirm:(id:string)=>void;produce:()=>void;review:(a:Asset)=>void;openReference:(r:Reference)=>void;notify:(s:string)=>void;dirty:(s:boolean)=>void};
export function downloadAsset(p:Project,a:Asset){
 const text="# "+p.name+"\n\n> CIS 首版预览 · 本地模板演示，不是AI生成或正式产品内容。\n\n"+a.text+"\n\n---\n输入版本："+a.revision+"\n产物版本："+a.id+"\n审核："+a.status+"\n备注："+a.note;
 const url=URL.createObjectURL(new Blob([text],{type:"text/markdown;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="cis-preview-"+a.id+".md";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function ProductForm({p,a}:{p:Project;a:Actions}){
 const[value,setValue]=useState(p.product);
 return <div className="editor-layout"><section className="editor-pane"><div className="section-title"><h2>当前创作对象</h2><span className="badge">项目输入 · B</span></div><form onSubmit={e=>{e.preventDefault();a.dirty(false);a.input({product:value.trim(),bound:true});}}><label className="field">产品或创作对象 <span>必填</span><input required maxLength={120} value={value} onChange={e=>{setValue(e.target.value);a.dirty(true);}} placeholder="例如：当前项目的跑步随身装备"/></label><p className="field-help">此处只保存当前项目输入，不会建立正式产品知识。</p><Button primary type="submit"><Check size={16}/>{p.bound?"保存项目输入":"确认项目输入"}</Button></form><div className="fact-list">{["材料 / 工艺","尺寸 / 重量","功能 / 性能","正式知识版本"].map(s=><div key={s}><span>{s}</span><b>UNKNOWN</b><span className="badge">U · 未知</span></div>)}</div></section><aside className="context-panel"><BookOpen size={24}/><h3>先确认什么是真的</h3><p>正式知识源尚未连接。材料、功能与性能保持未知，摄影参考不作为产品事实。</p><div className="notice">知识平台 · 未连接</div><StepLink href="#/settings">查看接入状态</StepLink></aside></div>;
}
export function IntentForm({p,a}:{p:Project;a:Actions}){
 const[brief,setBrief]=useState(p.brief),[audience,setAudience]=useState(p.audience),[output,setOutput]=useState(p.output);
 function submit(e:FormEvent){e.preventDefault();a.dirty(false);a.input({brief:brief.trim(),audience:audience.trim(),output,confirmed:true});}
 return <div className="editor-layout"><form className="editor-pane" onSubmit={submit}><label className="field">这次想做什么？ <span>必填</span><textarea rows={7} required maxLength={3000} value={brief} onChange={e=>{setBrief(e.target.value);a.dirty(true);}} placeholder="描述创作目标、希望传达的感受，以及不希望出现的表达…"/></label><div className="field-grid"><label className="field">面向谁<input value={audience} maxLength={200} onChange={e=>{setAudience(e.target.value);a.dirty(true);}} placeholder="描述目标受众"/></label><label className="field">输出类型<select value={output} onChange={e=>{setOutput(e.target.value);a.dirty(true);}}><option>文案</option><option>图片</option><option>视频</option></select></label></div><div className="form-footer"><span className="field-help">确认后可以继续选择参考。更改需求将使旧方向确认失效。</span><Button primary type="submit">保存并确认<ArrowRight size={16}/></Button></div></form><aside className="context-panel"><span className="small-label">BRIEF / {p.confirmed?"已确认":"待填写"}</span><h3>把意图说清楚</h3><ol><li>这次创作要解决什么？</li><li>希望观看者记住什么？</li><li>哪些表达必须避免？</li></ol><p>首版保留你的原始输入。AI 需求解析尚未接入。</p></aside></div>;
}
export function ReferenceView({p,a,setOnly=false}:{p?:Project;a:Actions;setOnly?:boolean}){
 const[q,setQ]=useState(""),[theme,setTheme]=useState("全部");
 const shown=references.filter(r=>(!setOnly||p?.refs.includes(r.id))&&(theme==="全部"||r.theme===theme)&&[r.name,r.theme,r.dimension].join(" ").includes(q));
 return <><div className="filter-strip"><div className="chips">{["全部","动态","光影","材质"].map(t=><button className={theme===t?"active":""} aria-pressed={theme===t} key={t} onClick={()=>setTheme(t)}>{t}</button>)}</div><input className="filter-input" aria-label="搜索摄影参考" placeholder="搜索名称、光线、构图…" value={q} onChange={e=>setQ(e.target.value)}/><span className="small-label">{shown.length} 项参考</span></div>{shown.length?<div className="reference-grid">{shown.map(r=><ReferenceCard key={r.id} r={r} selected={p?.refs.includes(r.id)} onOpen={()=>a.openReference(r)} onToggle={p&&!p.archived?()=>a.input({refs:p.refs.includes(r.id)?p.refs.filter(id=>id!==r.id):[...p.refs,r.id]}):undefined}/>)}</div>:<Empty title={setOnly?"组合中还没有参考":"没有匹配的参考"} description={setOnly?"从摄影参考中选择值得借鉴的构图、光线或动态。":"尝试更短的关键词，或清除当前筛选。"}><Button onClick={()=>{setQ("");setTheme("全部");}}>清除筛选</Button>{setOnly&&p&&<StepLink href={"#/projects/"+p.id+"/references"}>去发现参考</StepLink>}</Empty>}{p&&p.refs.length>0&&<div className="selection-bar"><span><b>{p.refs.length}</b> 项参考已加入当前组合</span><StepLink href={"#/projects/"+p.id+(setOnly?"/analysis":"/reference-set")}>{setOnly?"查看创意分析":"打开参考组合"}</StepLink></div>}<p className="caption">摄影仅用于视觉参考。分析说明为编辑示例，非真实模型输出。</p></>;
}
export function StageView({stage,p,a}:{stage:Stage;p:Project;a:Actions}){
 const base="#/projects/"+p.id;const direction=directions.find(d=>d.id===p.direction);
 if(stage==="product")return <ProductForm p={p} a={a}/>;
 if(stage==="intent")return <IntentForm p={p} a={a}/>;
 if(stage==="references"||stage==="reference-set")return <ReferenceView p={p} a={a} setOnly={stage==="reference-set"}/>;
 if(stage==="analysis")return p.refs.length?<><div className="analysis-intro"><span className="badge">编辑示例 · 非 AI 分析</span><p>拆解视觉机制，而不是照搬画面。</p></div>{references.filter(r=>p.refs.includes(r.id)).map((r,i)=><article className="analysis-row" key={r.id}><Photo src={r.image} alt={r.name}/><div><span className="small-label">0{i+1} / {r.theme}</span><h2>{r.name}</h2><p>{r.description}</p><div className="analysis-facts"><span>可借鉴：{r.dimension}</span><span>传播表现：未知</span></div><button className="text-link" onClick={()=>a.openReference(r)}>查看来源<ArrowUpRight size={16}/></button></div></article>)}<StepLink href={base+"/directions"}>探索创意方向</StepLink></>:<Empty title="从一组参考开始" description="选择参考后，可以查看对应的视觉拆解示例。"><StepLink href={base+"/references"}>发现参考</StepLink></Empty>;
 if(stage==="directions")return <><div className="direction-summary"><p>三种表达，各有取舍。</p><span className="badge">预设方向 · 待你判断</span></div>{directionGate(p)&&<div className="notice"><Info size={16}/>{directionGate(p)}。仍可浏览所有方向。</div>}<div className="direction-grid">{directions.map(d=>{const r=references.find(r=>r.id===d.ref)!;const selected=p.direction===d.id;return <article className={"direction-card "+(selected?"chosen":"")} key={d.id}><Photo src={r.image} alt={r.name}/><div className="direction-body"><div className="direction-number"><span>{d.number}</span>{selected?<span className="badge">{canProduce(p)?"已确认":"需重新确认"}</span>:<span>{d.en}</span>}</div><h2>{d.name}</h2><p>{d.summary}</p><dl><div><dt>视觉语言</dt><dd>{d.light}</dd></div><div><dt>执行复杂度</dt><dd>{d.execution}</dd></div><div><dt>创新方式</dt><dd>{d.originality}</dd></div><div><dt>需要关注</dt><dd>{d.risk}</dd></div></dl><Button primary={selected} disabled={!!directionGate(p)} onClick={()=>a.confirm(d.id)}>{selected&&canProduce(p)?<Check size={16}/>:<ArrowRight size={16}/>} {selected&&canProduce(p)?"已确认此方向":"选择并确认"}</Button></div></article>})}</div>{direction&&<div className="selection-bar"><span>当前方向：<b>{direction.name}</b></span><StepLink href={base+"/board"}>打开创意板</StepLink></div>}</>;
 if(stage==="board")return direction?<><div className="creative-board"><div className="board-statement"><span className="small-label">DIRECTION / {direction.en}</span><h2>{direction.name}</h2><p>{direction.strategy}</p><span className="badge">{canProduce(p)?"方向已确认":"输入已改变 · 需重新确认"}</span></div><div className="board-photos">{references.filter(r=>p.refs.includes(r.id)).map(r=><button key={r.id} onClick={()=>a.openReference(r)}><Photo src={r.image} alt={r.name}/><span>{r.theme} / {r.name}</span></button>)}</div></div><div className="board-notes"><section><h3>产品表达</h3><p>{p.product||"未确认"}</p><small>项目输入；不作为正式知识</small></section><section><h3>视觉约束</h3><p>{direction.light}</p><small>{direction.risk}</small></section><section><h3>创作需求</h3><p>{p.brief}</p></section></div><StepLink href={base+(canProduce(p)?"/production":"/directions")}>{canProduce(p)?"进入生产工作室":"重新确认方向"}</StepLink></>:<Empty title="先确定一个创意方向" description="创意板将汇集你选定的方向、参考和创作约束。"><StepLink href={base+"/directions"}>比较方向</StepLink></Empty>;
 if(stage==="production")return <div className="editor-layout"><section className="editor-pane"><div className="section-title"><h2>将方向转为产物</h2><span className="badge">本地演示</span></div><div className="production-summary"><FileText size={32}/><div><h3>{p.output}制作</h3><p>{direction?.name||"尚未确认方向"}</p></div></div><dl className="detail-list"><div><dt>输入版本</dt><dd>r{p.revision}</dd></div><div><dt>参考组合</dt><dd>{p.refs.length} 项</dd></div><div><dt>正式生成服务</dt><dd>未连接</dd></div><div><dt>本地演示费用</dt><dd>不调用付费服务</dd></div></dl>{!canProduce(p)&&<div className="notice">{directionGate(p)||"输入已变更或方向未确认，请重新确认方向。"}<StepLink href={base+"/directions"}>前往方向</StepLink></div>}<Button primary disabled={!canProduce(p)||p.output!=="文案"} onClick={a.produce}>制作文案演示<ArrowRight size={16}/></Button>{p.output!=="文案"&&<p className="field-help">图片与视频生成尚未连接。可以在创意需求中将输出改为文案，体验本地流程。</p>}<p className="caption">本地模板会使用当前需求与方向，不代表 AI 生成。制作后可体验审核与导出。</p>{p.assets.length>0&&<StepLink href={base+"/review"}>查看 {p.assets.length} 个演示产物</StepLink>}</section><aside className="context-panel"><LockKeyhole size={24}/><h3>确认过的输入，才进入生产</h3><p>每个产物保留制作时的输入版本。产品、需求或参考变更后，需要重新确认方向。</p><hr/><p>图片生成、视频编排与 NAS 保存将在真实服务接入后开放。</p><StepLink href="#/settings">查看接入状态</StepLink></aside></div>;
 if(stage==="review"||stage==="finals"){
 const assets=stage==="finals"?finals(p):p.assets;
 return assets.length?<><div className="section-line"><span>{assets.length} 个{stage==="finals"?"已通过演示产物":"演示产物"}</span><span>只保存在当前浏览器</span></div><div className="asset-grid">{assets.map((asset,i)=><article className="asset-card" key={asset.id}><div className="asset-preview"><span>TEXT / {String(i+1).padStart(2,"0")}</span><h3>{asset.text.split("\n")[0]}</h3><p>{asset.text.split("\n").slice(1).join("\n")}</p></div><div className="asset-meta"><span className={"badge "+(asset.status==="approved"?"success":"")}>{asset.status==="approved"?"人工通过":asset.status==="rejected"?"已淘汰":"待人工评审"}</span><span className="small-label">r{asset.revision}{asset.revision!==p.revision?" · 历史输入":""}</span></div><p className="caption">{asset.note||"尚无审核备注"}</p><div className="asset-actions">{stage==="review"?<Button disabled={p.archived} onClick={()=>a.review(asset)}>打开评审<ArrowUpRight size={16}/></Button>:<Button onClick={()=>downloadAsset(p,asset)}><Download size={16}/>导出文案</Button>}</div></article>)}</div></>:<Empty title={stage==="finals"?"把值得留下的创作，留在这里":"还没有待评审产物"} description={stage==="finals"?"人工通过的本地演示产物会出现在这里。尚未连接 NAS。":"先确认方向，再制作一份文案演示。"}><StepLink href={base+(stage==="finals"?"/review":"/production")}>{stage==="finals"?"前往评审":"前往生产工作室"}</StepLink></Empty>;
 }
 return null;
}
