"use client";
import {useState,type FormEvent} from "react";
import {Plus,Image as ImageIcon,ArrowRight} from "lucide-react";
import {average,isFeatured,reviewWork,type Studio,type Work,type DemoRole} from "../lib/studio";
import {Button,Empty,Heading,Modal,Photo} from "./ui";
import {DemoRoleBar,statusName} from "./skill-manager";
const categories=["产品展示","品牌视觉","电商广告","社交内容","人物场景"];
export function WorkLibrary({data,save,role,setRole}:{data:Studio;save:(s:Studio)=>boolean;role:DemoRole;setRole:(r:DemoRole)=>void}){
 const[tab,setTab]=useState("团队精选"),[q,setQ]=useState(""),[category,setCategory]=useState("全部"),[minimum,setMinimum]=useState("全部"),[state,setState]=useState("全部"),[sort,setSort]=useState("newest"),[upload,setUpload]=useState<Work|"new"|null>(null),[detail,setDetail]=useState<string|null>(null);
 const active=tab==="待审核"&&role!=="admin"?"我的作品":tab;
 const shown=data.works.filter(w=>(active==="我的作品"||role==="admin"&&active==="待审核"?active!=="待审核"||w.status==="pending":active==="团队精选"?isFeatured(w,data.threshold):w.status==="published")&&(category==="全部"||w.category===category)&&(state==="全部"||w.status===state)&&(minimum==="全部"||minimum==="待评分"?minimum!=="待评分"||w.scores===null:(average(w.scores)!==null&&average(w.scores)!>=Number(minimum)))&&(w.title+w.author+w.product).includes(q)).sort((a,b)=>sort==="score"?(average(b.scores)??-1)-(average(a.scores)??-1):b.createdAt.localeCompare(a.createdAt));
 const current=data.works.find(w=>w.id===detail);
 return <><Heading eyebrow="WORKS / 员工完成的图片" title="作品库" description="留下完成的作品，也留下让它变好的判断。" action={<Button primary onClick={()=>setUpload("new")}><Plus size={17}/>提交图片作品</Button>}/><DemoRoleBar role={role} setRole={setRole}/><div className="gallery-toolbar"><div className="tabs">{["团队精选","全部已发布","我的作品",...(role==="admin"?["待审核"]:[])].map(t=><button key={t} className={active===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</div><input className="filter-input" aria-label="搜索作品" value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索名称、作者、产品"/></div><div className="work-filters"><label>分类<select value={category} onChange={e=>setCategory(e.target.value)}><option>全部</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>质量评分<select value={minimum} onChange={e=>setMinimum(e.target.value)}>{["全部","待评分","3","4","5"].map(n=><option key={n} value={n}>{Number(n)?n+"分及以上":n}</option>)}</select></label><label>状态<select value={state} onChange={e=>setState(e.target.value)}><option value="全部">全部</option><option value="pending">待审核</option><option value="published">已发布</option><option value="rejected">已退回</option></select></label><label>排序<select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">最新提交</option><option value="score">评分优先</option></select></label>{role==="admin"&&<label>精选门槛（演示）<select aria-label="精选门槛" value={data.threshold} onChange={e=>save({...data,threshold:Number(e.target.value)})}>{[3,3.5,4,4.5,5].map(n=><option key={n}>{n}</option>)}</select></label>}</div><p className="caption">精选条件：人工审核通过、事实检查完成、质量均分 ≥ {data.threshold} / 5。未评分不计为0；真实投放表现单独记录。</p>{shown.length?<div className="masonry-grid work-masonry">{shown.map(w=><article className="inspiration-card" key={w.id}><button className="work-image" aria-label={"查看作品："+w.title} onClick={()=>setDetail(w.id)}><Photo src={w.image} alt={w.title}/></button><div className="inspiration-copy"><h3>{w.title}</h3><p>{w.author} · {w.category} · v{w.version}</p><div className="work-card-meta"><span className="badge">{statusName(w.status)}</span><strong>{average(w.scores)===null?"待评分":average(w.scores)+" / 5"}</strong></div><button className="text-link" onClick={()=>setDetail(w.id)}>查看作品与评分<ArrowRight size={15}/></button></div></article>)}</div>:<Empty title={data.works.length?"当前条件下没有作品":"让第一件作品，从这里留下来"} description="作品库只收员工完成并提交的图片。过程稿和文案留在我的项目，摄影素材请到参考库查看。"><Button onClick={()=>setUpload("new")}>提交图片作品</Button>{data.works.length>0&&<Button onClick={()=>{setTab("我的作品");setQ("");setCategory("全部");setMinimum("全部");setState("全部");}}>查看我的全部作品</Button>}</Empty>}
 {upload&&<Modal title={upload==="new"?"提交图片作品":"上传作品新版本"} onClose={()=>setUpload(null)}><WorkUpload previous={upload==="new"?undefined:upload} data={data} submit={w=>{if(save({...data,works:[w,...data.works]})){setUpload(null);setTab("我的作品");setState("全部");setMinimum("全部");}}}/></Modal>}
 {current&&<Modal title={current.title} wide onClose={()=>setDetail(null)}><div className="work-detail"><Photo src={current.image} alt={current.title}/><div><span className="badge">{statusName(current.status)} · v{current.version}</span><p>{current.author} · {current.category}</p><p>{current.product||"未关联产品"}</p><h3>创意质量</h3>{current.scores?<><dl className="detail-list">{["需求匹配","品牌一致性","视觉完成度","原创与参考转化"].map((s,i)=><div key={s}><dt>{s}</dt><dd>{current.scores![i]} / 5</dd></div>)}</dl><p>均分：{average(current.scores)} / 5</p><p>{current.reason}</p></>:<p className="muted">待评分，不参与评分排序与精选。</p>}<h3>真实投放表现</h3><p className="muted">尚未接入，没有曝光、点击或转化数据。</p><Button onClick={()=>{setUpload(current);setDetail(null);}}>上传新版本</Button><p className="caption">新版本重新审核和评分，保留当前版本及其记录。</p></div></div>{role==="admin"&&<WorkReview key={current.id+current.audit.length} work={current} onSave={w=>{if(save({...data,works:data.works.map(x=>x.id===w.id?w:x)}))setDetail(null);}}/>}{current.audit.length>0&&<details className="advanced-options"><summary>审核记录</summary>{current.audit.map((x,i)=><p key={i}>{new Date(x.at).toLocaleString("zh-CN")} · 管理员演示 · {statusName(x.action)}{x.scores?.length===4?" · 评分 "+x.scores.join(" / "):""}：{x.note}</p>)}</details>}</Modal>}</>;
}
function WorkReview({work,onSave}:{work:Work;onSave:(w:Work)=>void}){
 const[scores,setScores]=useState<number[]>(work.scores||[0,0,0,0]),[facts,setFacts]=useState(false),[note,setNote]=useState(""),[error,setError]=useState("");
 function decide(d:"published"|"rejected"){try{onSave(reviewWork(work,d,scores,facts,note,"admin",new Date().toISOString()));}catch(e){setError((e as Error).message);}}
 return <section className="work-review"><h3>管理员审核演示</h3><div className="work-filters">{["需求匹配","品牌一致性","视觉完成度","原创与参考转化"].map((s,i)=><label key={s}>{s}<select aria-label={s+"评分"} value={scores[i]} onChange={e=>setScores(scores.map((n,j)=>j===i?Number(e.target.value):n))}><option value={0}>请选择</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} 分</option>)}</select></label>)}</div><label className="inline-check"><input type="checkbox" checked={facts} onChange={e=>setFacts(e.target.checked)}/>已检查产品表达与已知资料，无未核实的事实主张</label><label className="field">评分与审核理由<textarea value={note} maxLength={2000} onChange={e=>setNote(e.target.value)} required/></label>{error&&<p className="notice error" role="alert">{error}</p>}<div className="modal-actions"><Button disabled={!note.trim()} onClick={()=>decide("rejected")}>退回修改</Button><Button primary disabled={!facts||scores.some(n=>n===0)||!note.trim()} onClick={()=>decide("published")}>确认评分并发布</Button></div></section>;
}
function WorkUpload({previous,data,submit}:{previous?:Work;data:Studio;submit:(w:Work)=>void}){
 const[title,setTitle]=useState(previous?.title||""),[category,setCategory]=useState(previous?.category||categories[0]),[product,setProduct]=useState(previous?.product||""),[image,setImage]=useState(""),[checked,setChecked]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function read(file:File|undefined){setImage("");setError("");if(!file)return;if(!["image/png","image/jpeg","image/webp"].includes(file.type)||file.size>700000){setError("请选择700 KB以内的PNG、JPEG或WebP图片。预览只保存浏览器本地副本。");return;}setLoading(true);try{const url=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error("图片读取失败"));r.readAsDataURL(file);});const img=new window.Image();img.src=url;await img.decode();if(!img.naturalWidth)throw new Error("无法识别图片");setImage(url);}catch{setError("图片无法读取，请换一张有效图片。");}finally{setLoading(false);}}
 function save(e:FormEvent){e.preventDefault();if(!image||!checked||!title.trim())return;const id=crypto.randomUUID();submit({id,family:previous?.family||id,version:previous?Math.max(...data.works.filter(w=>w.family===previous.family).map(w=>w.version))+1:1,title:title.trim(),category,product:product.trim(),author:"我（本地演示）",image,createdAt:new Date().toISOString(),status:"pending",scores:null,reason:"",factsChecked:false,audit:[]});}
 return <form onSubmit={save}><label className="field">作品名称<input required maxLength={80} value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="field-grid"><label className="field">分类<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="field">产品或项目<input maxLength={200} value={product} onChange={e=>setProduct(e.target.value)}/></label></div><label className="field">完成的图片（最大700 KB）<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void read(e.target.files?.[0])}/></label>{loading&&<p role="status">正在读取图片…</p>}{image&&<Photo className="upload-preview" src={image} alt="待提交作品预览"/>}<label className="inline-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>这是我完成且有权提交的图片作品</label><p className="caption">只保存在当前浏览器。提交不代表发布，须完成审核与评分。</p>{error&&<p className="notice error" role="alert">{error}</p>}<Button primary type="submit" disabled={loading||!image||!title.trim()||!checked}><ImageIcon size={16}/>提交作品审核</Button></form>;
}
